package com.ryan.citystory.mapper;

import com.ryan.citystory.bean.Persons;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PersonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int insert(Persons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    Persons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    List<Persons> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persons
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Persons record);
}